services:
  db:
    image: postgres:16
    container_name: shared_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shared_redis
    ports:
      - "6379:6379"

  polytech:
    profiles: [app]
    build:
      context: .
      dockerfile: polytech.Dockerfile
    container_name: polytech_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - erasmumu
      - mi8
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=school
      - ERASMUMU_URL=http://erasmumu:8081
      - MI8_GRPC_HOST=mi8
      - MI8_GRPC_PORT=8082

  erasmumu:
    profiles: [app]
    build:
      context: .
      dockerfile: erasmumu.Dockerfile
    container_name: erasmumu_app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=school

  mi8:
    profiles: [app]
    build:
      context: .
      dockerfile: mi8.Dockerfile
    container_name: mi8_app
    ports:
      - "8082:8082"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  postgres_data:
